### ISSUE TITLE
Shift+click for multiple selection

### ISSUE THREAD

**Issue by mlopezFC** [FlowingCode/GridHelpers#13]
After [this issue](https://github.com/FlowingCode/TwinColGridAddon/issues/13) is implemented, then it would be nice to use shift+click in order to select multiple items in each grid.

**Comment by javier-godoy** [comment]
This issue was originally reported in https://github.com/FlowingCode/TwinColGridAddon

**Comment by mthome** [comment]
FWIW, I needed to make some changes to the above code to get it to work properly with TwinColGrid and Vaadin 23 - in particular, while range select and simple click work, using control (or other bits) to deselect does not.  It looks to me like the selection state of the row changes before the listener is invoked.  As an example I would expect the following sequence of events to work:

1. click on row 2: it becomes selected
2. shift-click on row 4: rows 2,3,4 are selected
3. control-click on row 3: rows 2 and 4 only should be selected, but with the above code, the result is that row 3 stays selected.

I'm using the following code instead.  Note that this accepts various bits because many OS+browser combinations reserve control for their own purposes.

```
      grid.addItemClickListener(ev->{
            var clickedItem = ev.getItem();
            var bucky = ev.isCtrlKey() || ev.isMetaKey() || ev.isAltKey();

            if (!bucky) {
                grid.asMultiSelect().clear();
            }

            if (ev.isShiftKey()) {
                var lastClickedItem = ComponentUtil.getData(grid, "lastClickedItem");
                if (lastClickedItem!=null) {
                    var dataView = grid.getListDataView();
                    int index1 = dataView.getItems().collect(Collectors.toList()).indexOf(lastClickedItem);
                    int index2 = dataView.getItems().collect(Collectors.toList()).indexOf(clickedItem);

                    IntStream.rangeClosed(Math.min(index1, index2), Math.max(index1, index2))
                    .forEach(i -> grid.select(dataView.getItem(i)));
                    return;
                };
            }

            var isSelected = grid.asMultiSelect().isSelected(clickedItem);
            // the isSelected==bucky is a total hack to make both individual clicked items work and
            // for control/meta/alt-click to work as expected.
            // the original code just used !isSelected
            if (ev.isShiftKey() || (isSelected == bucky)) {
                ComponentUtil.setData(grid, "lastClickedItem", clickedItem);
                grid.select(clickedItem);
            } else {
                ComponentUtil.setData(grid, "lastClickedItem", null);
                grid.deselect(clickedItem);
            }
        });
```
